In [1]:
import pandas as pd

df = pd.read_csv('C:/Users/LENOVO/layoffs-data-analysis/data/raw/layoffs.csv')
df.shape

(4523, 11)

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4523 entries, 0 to 4522
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              4523 non-null   str
 1   location             4522 non-null   str
 2   total_laid_off       2960 non-null   float64
 3   date                 4523 non-null   str
 4   percentage_laid_off  2833 non-null   float64
 5   industry             4521 non-null   str
 6   source               4520 non-null   str
 7   stage                4516 non-null   str
 8   funds_raised         3990 non-null   float64
 9   country              4521 non-null   str
 10  date_added           4523 non-null   str
dtypes: float64(3), str(8)
memory usage: 388.8 KB

In [3]:
df.isnull().sum()

company                   0
location                  1
total_laid_off         1563
date                      0
percentage_laid_off    1690
industry                  2
source                    3
stage                     7
funds_raised            533
country                   2
date_added                0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df[['date', 'date_added']].isnull().sum()

date          1953
date_added    2012
dtype: int64

In [6]:
df_raw = pd.read_csv('C:/Users/LENOVO/layoffs-data-analysis/data/raw/layoffs.csv')
df_raw['date'].unique()[:20]

<StringArray>
[ '7/23/2026',  '7/22/2026',  '7/20/2026',  '7/19/2026',  '7/16/2026',
  '7/15/2026',  '7/13/2026', '07-12-2026', '07-11-2026', '07-08-2026',
 '07-07-2026', '07-06-2026', '07-03-2026', '07-01-2026',  '6/30/2026',
  '6/29/2026',  '6/26/2026',  '6/25/2026',  '6/24/2026',  '6/23/2026']
Length: 20, dtype: str

In [7]:
df_raw['date_added'].unique()[:20]

<StringArray>
[ '7/24/2026',  '7/23/2026',  '7/22/2026',  '7/20/2026',  '7/15/2026',
  '7/13/2026',  '7/14/2026', '07-12-2026', '07-09-2026', '07-10-2026',
 '07-08-2026', '07-06-2026', '07-11-2026', '07-05-2026', '07-03-2026',
 '07-01-2026',  '6/30/2026',  '6/27/2026',  '6/26/2026',  '6/25/2026']
Length: 20, dtype: str

In [8]:
df = pd.read_csv('C:/Users/LENOVO/layoffs-data-analysis/data/raw/layoffs.csv')
df['date'] = pd.to_datetime(df['date'], format='mixed', dayfirst=False)
df['date_added'] = pd.to_datetime(df['date_added'], format='mixed', dayfirst=False)
df[['date', 'date_added']].isnull().sum()

date          0
date_added    0
dtype: int64

In [9]:
df['date'] = df['date'].dt.strftime('%Y-%m-%d')
df['date_added'] = df['date_added'].dt.strftime('%Y-%m-%d')
df[['date', 'date_added']].head()

         date  date_added
0  2026-07-23  2026-07-24
1  2026-07-22  2026-07-24
2  2026-07-22  2026-07-23
3  2026-07-22  2026-07-24
4  2026-07-22  2026-07-24

In [10]:
df.dtypes

company                    str
location                   str
total_laid_off         float64
date                       str
percentage_laid_off    float64
industry                   str
source                     str
stage                      str
funds_raised           float64
country                    str
date_added                 str
dtype: object

In [11]:
df['company'] = df['company'].str.strip()
df['industry'].unique()

<StringArray>
[         'Media',         'Retail',        'Product', 'Transportation',
       'Hardware',         'Crypto',      'Marketing',           'Data',
        'Finance',       'Security',       'Consumer',         'Travel',
          'Legal',          'Other',      'Education',     'Healthcare',
             'HR',     'Recruiting',        'Support',    'Real Estate',
             'AI',           'Food',          'Sales',  'Manufacturing',
      'Logistics', 'Infrastructure',        'Fitness',         'Energy',
              nan,      'Aerospace',   'Construction']
Length: 31, dtype: str

In [12]:
df['country'].unique()

<StringArray>
[       'United States',               'Israel',       'Cayman Islands',
              'Nigeria',                'India',               'Canada',
          'Netherlands',       'United Kingdom',               'Brazil',
              'Ireland',            'Indonesia',            'Australia',
          'Switzerland',            'Singapore',              'Austria',
              'Germany',              'Denmark',               'Norway',
                'Egypt',               'Sweden', 'United Arab Emirates',
              'Estonia',                'Kenya',               'Cyprus',
          'New Zealand',       'Czech Republic',               'Turkey',
              'Uruguay',                'Japan',             'Portugal',
               'France',                'Malta',                  'UAE',
                'China',             'Pakistan',                'Spain',
              'Belgium',                'Chile',            'Lithuania',
               'Poland',              'Finland',              'Romania',
                    nan,                'Ghana',            'Hong Kong',
           'Luxembourg',               'Mexico',          'South Korea',
         'Saudi Arabia',          'Philippines',              'Ukraine',
                'Italy',             'Colombia',            'Argentina',
           'Seychelles',               'Greece',             'Malaysia',
              'Hungary',              'Vietnam',             'Thailand',
              'Senegal',                 'Peru',              'Bahrain',
               'Russia',             'Bulgaria',         'South Africa',
              'Myanmar']
Length: 67, dtype: str

In [13]:
df['stage'].unique()

<StringArray>
[      'Series F',       'Post-IPO',        'Unknown',       'Series G',
           'Seed',       'Acquired',       'Series D',       'Series B',
       'Series C', 'Private Equity',       'Series A',     'Subsidiary',
       'Series E',              nan,       'Series H',       'Series J',
       'Series I']
Length: 17, dtype: str

In [14]:
df['country'] = df['country'].replace('UAE', 'United Arab Emirates')
df['country'].nunique()

65

In [15]:
df = df.dropna(subset=['location','industry','source','stage','country'])
df.shape

(4508, 11)

In [16]:
df[['total_laid_off', 'funds_raised']].describe()

       total_laid_off   funds_raised
count     2956.000000    3984.000000
mean       313.667794     877.791440
std       1123.623295    4568.835994
min          3.000000       0.700000
25%         40.000000      55.000000
50%         90.000000     175.500000
75%        200.000000     484.000000
max      22000.000000  121900.000000

In [17]:
df['percentage_laid_off'].describe()

count    2825.000000
mean        0.292417
std         0.303063
min         0.000000
25%         0.100000
50%         0.170000
75%         0.330000
max         1.000000
Name: percentage_laid_off, dtype: float64

In [18]:
df['company'].nunique(), df['company'].str.lower().nunique()

(2932, 2924)

In [26]:
df['company_lower'] = df['company'].str.lower()
dupes = df.groupby('company_lower')['company'].unique()
dupes[dupes.apply(len) > 1]

Series([], Name: company, dtype: object)

In [27]:
canonical_names = df.groupby('company_lower')['company'].first()
df['company'] = df['company_lower'].map(canonical_names)
df['company'].nunique()

2924

In [28]:
df = df.drop(columns=['company_lower'])

In [22]:
df['location'].nunique(), df['location'].str.lower().nunique()
# df['industry'].nunique(), df['industry'].str.lower().nunique()
# df['stage'].nunique(), df['stage'].str.lower().nunique()

(272, 272)

In [24]:
df.to_csv('C:/Users/LENOVO/layoffs-data-analysis/data/cleaned/layoffs_cleaned.csv', index=False)